module_payment_credits = "Credits"
link_credits = "%d Credits"
msg_welcome_credits = "Du hast %s Willkommens-Credits erhalten!"
mt_payment_credits_order_credits = "Credits kaufen"
md_payment_credits_order_credits = "Wähle die Anzahl der Credits. Vor der Zahlung kannst du den Preis prüfen."
co_credits = "Credits kaufen"
msg_credits_purchase = "%d Credits kaufen"
cfg_paycreds_min_purchase = "Mindestkaufpreis (EUR)"
cfg_paycreds_rate = "Preis pro Credit (EUR)"
